<?php
# src/Repository/TestRepository.php

/**
 * Header - General Platform Template
 *
 * @author      Anzoumana SANOGO
 */

namespace sylax\Repository;

use Doctrine\ORM\EntityRepository;
use sylax\Entity\Test;
use sylax\Traits\GetManagerElement;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{
	/* your custom repositories here */
}